language: objective-c
os: osx
osx_image: xcode9.3
script:
  xcodebuild clean run -workspace Example/HSStockChart.xcworkspace -scheme HSStockChart-Example -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1' -enableCodeCoverage YES | xcpretty
podfile: Example/Podfile
